### ISSUE TITLE
0.4.0 might broke the Flatpak

### ISSUE THREAD

**Issue by tytan652** [flathub/com.obsproject.Studio.Plugin.Gstreamer#12]
Upstream issue: https://github.com/fzwoch/obs-gstreamer/issues/99

Default prefix and libdir was changed which have high chance to have break the Flatpak.

**Comment by fzwoch** [comment]
Yeah, sorry about that.

Btw, can't you add `--prefix` and `--libdir` here:

```
    config-opts:
      - --buildtype=release
```

Instead of patching it? Just thinking it seems more sane and future proof, unless I decide to break it again..

**Comment by marvin0815** [comment]
No worries, i'll look into it. It's a quick fix because I don't like to have a broken flatpak published.

**Comment by marvin0815** [comment]
I didn't try `libdir` as a relative path. That did the trick. Thank you.
