### ISSUE TITLE
Does not work with: gstreamer-vaapi 22.08

### ISSUE THREAD

**Issue by RickAndTired** [flathub/com.obsproject.Studio.Plugin.Gstreamer#8]
There are two flatpak versions of gstreamer-vaapi 
runtime/org.freedesktop.Platform.GStreamer.gstreamer-vaapi/x86_64/21.08
runtime/org.freedesktop.Platform.GStreamer.gstreamer-vaapi/x86_64/22.08

OBS Studio Gstreamer plugin does not work with `org.freedesktop.Platform.GStreamer.gstreamer-vaapi/x86_64/22.08`

**Comment by marvin0815** [comment]
Sorry, issue closed for the wrong reason.

All KDE flatpak runtimes are based on 21.08 for now (https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt6.3/org.kde.Sdk.json.in#L8), even the QT6 based. This is just how flatpak works.
